version: "3.7"
services:
  webserver:
    image: puckel/docker-airflow:latest
    restart: always
    entrypoint: /usr/local/etl/entrypoint.sh
    env_file:
      - .env
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    volumes:
      - /root/airflow_perosnal/airflow_pdf_etl/airflow:/usr/local/airflow
      - /root/airflow_perosnal/airflow_pdf_etl:/usr/local/etl
      - ./requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
    networks:
    - mynet
    command: webserver
    depends_on:
      - tikaserver
      - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://elasticsearch:9200"]
      interval: 30s
      timeout: 30s
      retries: 3
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
    - mynet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 60s
      timeout: 30s
      retries: 3


  tikaserver:
    image: logicalspark/docker-tikaserver
    ports:
      - "9998:9998"
    networks:
    - mynet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9998"]
      interval: 60s
      timeout: 30s
      retries: 3

networks:
  mynet:
    driver: bridge
    ipam:
      driver: default
